#!/usr/bin/env python3
"""Emit talk/numbers.tex from the evidence artifact.

The manuscript binds every headline number to evaluation/results/final_summary.json through
\\artv sites, and paper/scripts/check_banlist.py refuses to build when one disagrees. A deck
retyped by hand has no such guard and is exactly where a stale number survives: the slide is
written once, the artifact moves, and nobody re-reads the slide. So the deck reads the same
artifact. If a number moves, `make -C talk` regenerates and the slide moves with it.

    python talk/gen_numbers.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "evaluation" / "results" / "final_summary.json"
ALONGTRACK = ROOT / "evaluation" / "real_data" / "l47_alongtrack.json"
CURVE = ROOT / "evaluation" / "results" / "l47_power_curve.json"
OUT = Path(__file__).resolve().parent / "numbers.tex"


def main() -> int:
    s = json.loads(SUMMARY.read_text())
    at = json.loads(ALONGTRACK.read_text())
    curve = {c["icc"]: c["halt_prob"] for c in json.loads(CURVE.read_text())["curve"]}

    c, r = s["l47_calibration"], s["real_l47_application"]
    a, e, x = s["real_l47_alongtrack"], s["external_artifact_study"], s["external_consequence"]
    lo, hi = c["clean_false_halt_wilson_95"]
    d1 = at["analyses"]["D1_pass_in_elementset"]

    v = {
        # calibration
        "Nrate": c["measured_clean_false_halt_rate"],
        "Nwlo": lo, "Nwhi": hi,
        "Nalpha": c["nominal_alpha"],
        "Ncleanpaths": c["clean_paths_evaluated"],
        "Ncleanhalts": c["clean_false_halts"],
        "Nseeds": json.loads(CURVE.read_text())["n_seeds_per_point"],
        "Npowerlo": curve[0.2], "Npowerhi": curve[0.8],
        # real orbital
        "Nobjects": r["n_objects"], "Nelsets": r["n_element_sets"], "Npasses": r["n_passes"],
        "Naticc": a["D1_pass_in_elementset"]["icc"],
        "Natp": d1["p_value"], "Natlo": d1["icc_lower_95_one_sided"],
        "Naticcobj": a["D2_pass_in_object"]["icc"],
        "Naticcelset": a["D3_elementset_in_object"]["icc"],
        "Natused": a["n_passes_used"], "Natelsets": a["n_elsets"],
        "Natmedian": a["intrack_abs_km"]["median"], "Natmax": a["intrack_abs_km"]["max"],
        # third-party
        "Nextpass": e["pass"], "Nexthalt": e["halt"], "Nextindet": e["indeterminate"],
        "Nextna": e["not_applicable"], "Nextnobs": e["not_observable"],
        "Nextrules": e["n_rules_classified"],
        "Nconsseeds": x["n_seeds"], "Nconschanged": x["n_seeds_selection_changed"],
        "Nconsminp": x["downstream_min_attainable_p"],
        # contract
        "Nrules": s["rule_count"], "Nfaults": s["fault_class_count"],
        "Nred": s["detectors_with_red_fixture"], "Nloc": s["source_loc"],
        "Nobjprot": s["protected_object_count"],
    }
    body = "\n".join(rf"\newcommand{{\{k}}}{{{val}}}" for k, val in v.items())
    OUT.write_text(
        "% GENERATED by talk/gen_numbers.py -- do not edit.\n"
        "% Every slide number is read from evaluation/results/final_summary.json, the same\n"
        "% artifact the manuscript's claim gate checks against. Retyping one here would\n"
        "% reintroduce exactly the drift that gate exists to prevent.\n"
        + body + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(v)} values)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
